define preprule_dfy =
$(3): $(2) | prepare
	$(call build_cmd,DFY,$(1),$(3),\
		dafny /compile:0 /spillTargetCode:3 /compileTarget:cpp $(2) /out:$(3)	
	)

UK_SRCS-y += $(2)
$(eval $(call vprefix_lib,$(1),CLEAN-y) += $(call build_clean,$(3)))
endef
